import:
  - ~/.config/alacritty/fonts.yml

window:
  padding:
    x: 12
    y: 12

  decorations: none
  opacity: 1.0
  dynamic_title: true

colors:
  primary:
    background: '#0f1012'
    foreground: '#b2b2b2'

  normal:
    black:  '#000000'
    red: '#df013a'
    green: '#01df74'
    yellow: '#fafa58'
    blue: '#8181f7'
    magenta: '#fe2e9a'
    cyan: '#81bef7'
    white: '#f2f2f2'

live_config_reload: true
