#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#xrandr --output DP-4 --mode 1920x1080 -r 144.00

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        0
bspc config window_gap          4

bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle	 true
bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner
bspc config top_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

procs=("sxhkd" "picom" "polybar")

for processes in "${procs[@]}"; do
	pkill -9 -f "$processes"
done
picom --config "$HOME/.config/bspwm/picom.conf" &
polybar -c "$HOME/.config/polybar/config.ini" &
feh -z --no-fehbg --bg-fill --scale-down "$HOME/.config/bspwm/walls" &
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
xsetroot -cursor_name left_ptr & 
